name: Auto deploy dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} #hostname of server
          username: ${{ secrets.USERNAME }} #username login to server
          password: ${{ secrets.PASSWORD }} #password login to server
          port: ${{ secrets.PORT }} #port of server - often port is 22
          script: | # run with multiple script
            cd uat-ldz/app/summer-activities-for-kids-back-end/
            git pull origin develop
            mvn clean install
            docker build -t summer-activity .
            cd ~
            cd uat-ldz/docker-compose/app-summer-activity/
            docker-compose up -d
