name: Auto deploy dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} #hostname of server
          username: ${{ secrets.USERNAME }} #username login to server
          password: ${{ secrets.PASSWORD }} #password login to server
          port: ${{ secrets.PORT }} #port of server - often port is 22
          script: | # run with multiple script
            cd worker/auto-deploy-project-with-action/
            git pull origin master
            mvn clean install
            docker build -t auto-deploy .
            docker-compose up -d
